/* 
 * File:   main.cpp
 * Author: Ngoc Huynh
 * Created on March 30th, 2018, 4:13 PM
 * Purpose:  This program calculates salary of each day and total after a period of time
 */

//System Libraries
#include <iostream>
#include <cstdlib>
using namespace std;

//User Libraries

//Global Constants - Math/Physics Constants, Conversions,
//                   2-D Array Dimensions

//Function Prototypes

//Execution Begins Here
int main(int argc, char** argv) {
    //Declare Variables
    int x, // user inputs guessing number
        rndnum; // random number generated by the program
    
    srand(static_cast<unsigned int>(time(0)));
    
    rndnum = rand()%999+1; //[1,999]
    cout << "Guess a number from 1 - 999.";
    
    while (x != rndnum)
    {
        cin >> x;
        if (x > rndnum)
            cout << "Too high, try again." << endl;
        else if (x < rndnum)
            cout << "Too low, try again." << endl;
        else
            cout << "You guessed it right!" << endl;
    }
    
     
    //Exit stage right!
    return 0;
}