/* 
 * File:   main.cpp
 * Author: Ngoc Huynh
 * Created on May 6, 2018, 6:28 PM
 * Purpose:  This program simulates the tossing of a coin
 */

//System Libraries
#include <iostream>
#include <cstdlib>
using namespace std;

//User Libraries

//Global Constants - Math/Physics Constants, Conversions,
//                   2-D Array Dimensions

//Function Prototypes
int coinToss(void);

//Execution Begins Here

        
int main(int argc, char** argv) {
//Process/Map inputs to outputs
  int   x, // number of time of tossing of the coin 
        rndnum; // random number generated by the program
    unsigned seed = time (0);
    srand (seed); 
    srand(static_cast<unsigned int>(time(0)));
    x = rndnum = 0;
    
    rndnum = rand()%2+1; //[1,2]
    return rndnum;
    cout << "How many number do you want to toss the coin?" << endl;
    cin >> x;
    
    for (int i = 1 ; i <= x; i++){
        rndnum = coinToss();
        if (rndnum == 1 )
            cout << "Heads" << endl;
        if (rndnum == 2)
            cout << "Tail" << endl;
    }
}
    
//Exit stage right!